### ISSUE TITLE
Create separate function (or module) for creating new router.

### ISSUE THREAD

**Issue by thinkofher** [hakierspejs/long-season#29]
Right now we are declaring router in the main function of `cmd/server`, which is obviously only temporary solution. My proposition is:

- Create the separate function, which returns `http.Handler` in handlers package or,
- create the separate `router` module with `router.New` function, which returns `http.Handler`.

**Comment by bikerwhocodes** [comment]
I would suggest creating a separate go file for handlerfuncs and use main.go to call those functions (as a router).
