### ISSUE TITLE
Change name of long-season cli tool in docker image

### ISSUE THREAD

**Issue by thinkofher** [hakierspejs/long-season#55]
Change name of `long-season` cli tool from `long-season-cli` to `short-season` in docker container image.

**Comment by rajkumarGosavi** [comment]
Hi, 
I am interested. Can you share more details

**Comment by thinkofher** [comment]
Just change `long-season-cli` in below Dockerfile recipe to actual name of cli tool, which is `short-season` :).

https://github.com/hakierspejs/long-season/blob/818166cb87673d0a02a0207657e3218c6f59cb5d/Dockerfile#L19-L20

If you're going to grab this issue, please make sure that there is no other use of `long-season-cli` name in project with grep or whatever you're using.

Thank you for your interest in `long-season` 👾

**Comment by rajkumarGosavi** [comment]
https://github.com/hakierspejs/long-season/pull/58 Please review the PR

**Comment by thinkofher** [comment]
closed by #58
